import {
  boolean,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  smallint,
  text,
  timestamp,
  uuid,
  bigserial,
} from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
};

export const appUsers = pgTable("app_users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  displayName: text("display_name").notNull(),
  timezone: text("timezone").notNull().default("Asia/Jakarta"),
  currencyCode: text("currency_code").notNull().default("IDR"),
  dailyCapacityMinutes: integer("daily_capacity_minutes").notNull().default(240),
  ...timestamps,
});

export const goals = pgTable("goals", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  parentGoalId: uuid("parent_goal_id"),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  periodType: text("period_type").notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
  targetValue: numeric("target_value", { precision: 18, scale: 2 }),
  currentValue: numeric("current_value", { precision: 18, scale: 2 }).notNull().default("0"),
  unit: text("unit"),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("active"),
  successCriteria: text("success_criteria"),
  ...timestamps,
});

export const revenueEngines = pgTable("revenue_engines", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  name: text("name").notNull(),
  description: text("description"),
  incomeType: text("income_type").notNull(),
  monthlyTarget: numeric("monthly_target", { precision: 18, scale: 2 }).notNull().default("0"),
  status: text("status").notNull().default("idea"),
  isRecurring: boolean("is_recurring").notNull().default(false),
  averageTicketSize: numeric("average_ticket_size", { precision: 18, scale: 2 }).notNull().default("0"),
  targetCustomer: text("target_customer"),
  startDate: date("start_date"),
  reviewDate: date("review_date"),
  ...timestamps,
});

export const projects = pgTable("projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  goalId: uuid("goal_id").references(() => goals.id),
  revenueEngineId: uuid("revenue_engine_id").references(() => revenueEngines.id),
  name: text("name").notNull(),
  description: text("description"),
  projectType: text("project_type").notNull(),
  status: text("status").notNull().default("idea"),
  priority: text("priority").notNull().default("medium"),
  startDate: date("start_date"),
  targetCompletionDate: date("target_completion_date"),
  actualCompletionDate: date("actual_completion_date"),
  estimatedHours: numeric("estimated_hours", { precision: 10, scale: 2 }).notNull().default("0"),
  actualHours: numeric("actual_hours", { precision: 10, scale: 2 }).notNull().default("0"),
  revenuePotential: numeric("revenue_potential", { precision: 18, scale: 2 }).notNull().default("0"),
  actualRevenue: numeric("actual_revenue", { precision: 18, scale: 2 }).notNull().default("0"),
  successCriteria: text("success_criteria"),
  stopCriteria: text("stop_criteria"),
  healthStatus: text("health_status").notNull().default("healthy"),
  lastActivityAt: timestamp("last_activity_at", { withTimezone: true }),
  ...timestamps,
});

export const revenueTransactions = pgTable("revenue_transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  revenueEngineId: uuid("revenue_engine_id").notNull().references(() => revenueEngines.id),
  projectId: uuid("project_id").references(() => projects.id),
  transactionType: text("transaction_type").notNull(),
  amount: numeric("amount", { precision: 18, scale: 2 }).notNull(),
  occurredOn: date("occurred_on").notNull(),
  description: text("description").notNull(),
  source: text("source").notNull().default("manual"),
  ...timestamps,
});

export const projectScores = pgTable("project_scores", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  revenuePotential: smallint("revenue_potential").notNull(),
  speedToRevenue: smallint("speed_to_revenue").notNull(),
  marketDemand: smallint("market_demand").notNull(),
  skillFit: smallint("skill_fit").notNull(),
  easeOfValidation: smallint("ease_of_validation").notNull(),
  probabilityOfCompletion: smallint("probability_of_completion").notNull(),
  recurringIncomePotential: smallint("recurring_income_potential").notNull(),
  strategicFit: smallint("strategic_fit").notNull(),
  assetCreationPotential: smallint("asset_creation_potential").notNull(),
  complexity: smallint("complexity").notNull(),
  riskScore: smallint("risk_score").notNull(),
  totalScore: numeric("total_score", { precision: 6, scale: 2 }).notNull(),
  recommendation: text("recommendation").notNull(),
  overrideReason: text("override_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  projectId: uuid("project_id").references(() => projects.id),
  goalId: uuid("goal_id").references(() => goals.id),
  revenueEngineId: uuid("revenue_engine_id").references(() => revenueEngines.id),
  name: text("name").notNull(),
  description: text("description"),
  status: text("status").notNull().default("inbox"),
  priority: text("priority").notNull().default("medium"),
  startDate: date("start_date"),
  dueDate: date("due_date"),
  estimatedMinutes: integer("estimated_minutes").notNull().default(0),
  actualMinutes: integer("actual_minutes").notNull().default(0),
  revenueImpact: smallint("revenue_impact").notNull().default(0),
  strategicImpact: smallint("strategic_impact").notNull().default(0),
  urgency: smallint("urgency").notNull().default(0),
  priorityScore: numeric("priority_score", { precision: 8, scale: 2 }),
  isDailyPriority: boolean("is_daily_priority").notNull().default(false),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  ...timestamps,
});

export const taskOutputs = pgTable("task_outputs", {
  id: uuid("id").primaryKey().defaultRandom(),
  taskId: uuid("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  name: text("name").notNull(),
  description: text("description"),
  outputType: text("output_type"),
  priority: text("priority").notNull().default("medium"),
  weight: integer("weight").notNull().default(20),
  isMandatory: boolean("is_mandatory").notNull().default(true),
  status: text("status").notNull().default("pending"),
  dueDate: date("due_date"),
  evidenceUrl: text("evidence_url"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const timeEntries = pgTable("time_entries", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => appUsers.id),
  taskId: uuid("task_id").references(() => tasks.id),
  projectId: uuid("project_id").references(() => projects.id),
  revenueEngineId: uuid("revenue_engine_id").references(() => revenueEngines.id),
  entryDate: date("entry_date").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  endedAt: timestamp("ended_at", { withTimezone: true }),
  durationMinutes: integer("duration_minutes").notNull(),
  activityCategory: text("activity_category").notNull(),
  isBillable: boolean("is_billable").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  userId: uuid("user_id").references(() => appUsers.id),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: uuid("entity_id"),
  oldValues: jsonb("old_values"),
  newValues: jsonb("new_values"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
